### ISSUE TITLE
color constants

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/StellarGameEngine#1]
Isn't it better to use c_colorname instead of just the name of the color?

**Comment by onpon4** [comment]
I honestly think not. It doesn't make anything more easy or more clear. Game Maker needs these constants because of the way it handles colors, but we don't because we can just use strings. The specification allows users to enter e.g. "red" for a color, and the engine silently searches for it in COLORS, at least hypothetically (though it is also perfectly possible to pass the color name directly to the graphics library, for instance).

I also have a bit of a problem with using constants because the normal way to import SGE would be simply "import sge", so if we use constants, "sge." would have to precede each constant It's not that big of a deal, but I think it looks uglier.

Of course, I'm open to discussion about this, but I think accepting strings with color names is easier than having constants for them.

**Comment by coppolaemilio** [comment]
Well I think that make sense that we don't have to use the "sge." but it makes me feel weird coding colors using strings :P Isn't any other way to getting this?
About the names I think that adding the "c_" before the names makes it easy to avoid confusion with other variables or strings that have color names but are not colors. So the distinction will be in this case "c_" like in the use of "spr_" for sprite "obj_" for objects etc...

If it has to be a string I prefer "c_colorname" instead of just "colorname"

**Comment by onpon4** [comment]
"c_colorname" (as a string) is definitely a bad idea and unnecessary. The colors are based on HTML colors, which do not add an extra bit to the string like that, and that extra bit is not obvious to those who have not used Game Maker.

The whole use of prefixes found in Game Maker is a bit unusual in Python, especially when it is unnecessary.

As for not liking programming it, that's what the COLORS dictionary is for; you don't need to program it. All you need to do is change the color to the corresponding color in the dictionary. For example:

if color.lower() in COLORS: color = COLORS[color.lower()]

You can then proceed to figure out if it's an HTML hex string, a hex number, or a tuple and interpret it as normal.

**Comment by coppolaemilio** [comment]
You are right :+1:  

I'm just so used to Game Maker.... :P
